export const INIT = {
  T1:[
    { id:"t1-1", name:"Python (advanced)", freq:5,
      topics:[
        {t:"Async / await patterns",s:"have"},{t:"Type hints & dataclasses",s:"have"},
        {t:"Packaging & virtual envs",s:"have"},{t:"Decorators, generators",s:"have"},
        {t:"Testing with pytest",s:"have"},
      ], tools:"fastapi · pydantic · asyncio · pytest" },
    { id:"t1-2", name:"LLM APIs & prompt engineering", freq:5,
      topics:[
        {t:"OpenAI, Anthropic, Gemini APIs",s:"have"},{t:"System prompts & roles",s:"have"},
        {t:"Few-shot & chain-of-thought",s:"have"},{t:"Structured outputs (JSON mode)",s:"have"},
        {t:"Token counting & cost control",s:"have"},
      ], tools:"openai · anthropic · tiktoken · litellm" },
    { id:"t1-3", name:"LangChain", freq:5,
      topics:[
        {t:"Chains & LCEL (pipe syntax)",s:"have"},{t:"Tools & agent executors",s:"have"},
        {t:"Memory & conversation history",s:"have"},{t:"Document loaders & splitters",s:"have"},
        {t:"Callbacks & tracing hooks",s:"have"},
      ], tools:"langchain · langchain-community · langchain-core" },
    { id:"t1-4", name:"LangGraph", freq:4,
      topics:[
        {t:"StateGraph nodes & edges",s:"have"},{t:"Conditional routing",s:"have"},
        {t:"Checkpointers & persistence",s:"have"},{t:"Subgraphs & parallelism",s:"todo"},
        {t:"Human-in-the-loop patterns",s:"learn"},
      ], tools:"langgraph · StateGraph · MemorySaver" },
    { id:"t1-5", name:"RAG pipelines", freq:5,
      topics:[
        {t:"Chunking strategies (fixed, semantic)",s:"have"},{t:"Embedding models selection",s:"have"},
        {t:"Retrieval (dense + sparse)",s:"have"},{t:"Re-ranking with cross-encoders",s:"learn"},
        {t:"Hybrid search & MMR",s:"learn"},
      ], tools:"langchain · llama-index · haystack · cohere rerank" },
    { id:"t1-6", name:"Vector databases", freq:5,
      topics:[
        {t:"Pinecone index ops & namespaces",s:"todo"},{t:"Weaviate schema & vectorizer",s:"todo"},
        {t:"pgvector with PostgreSQL",s:"todo"},{t:"Chroma for local dev",s:"have"},
        {t:"HNSW index tuning",s:"todo"},
      ], tools:"pinecone · weaviate-client · pgvector · chromadb" },
    { id:"t1-7", name:"Embeddings & semantic search", freq:4,
      topics:[
        {t:"OpenAI text-embedding-3",s:"have"},{t:"Sentence-transformers (BGE, E5)",s:"have"},
        {t:"Cosine similarity & ANN",s:"have"},{t:"Fine-tuning embedding models",s:"todo"},
        {t:"Dimensionality & trade-offs",s:"todo"},
      ], tools:"sentence-transformers · faiss-cpu · openai embeddings" },
  ],
  T2:[
    { id:"t2-1", name:"Multi-agent orchestration", freq:5,
      topics:[
        {t:"Supervisor + worker patterns",s:"learn"},{t:"Agent-to-agent delegation",s:"learn"},
        {t:"Shared vs private state",s:"todo"},{t:"Interrupt & approval gates",s:"todo"},
        {t:"Parallel subgraph execution",s:"todo"},
      ], tools:"langgraph · autogen · crewai · google-adk" },
    { id:"t2-2", name:"Tool use & function calling", freq:5,
      topics:[
        {t:"OpenAI / Anthropic tool schemas",s:"have"},{t:"Pydantic output validation",s:"have"},
        {t:"Parallel tool calls",s:"have"},{t:"Tool error handling & retries",s:"learn"},
        {t:"Instructor library patterns",s:"learn"},
      ], tools:"openai tools · anthropic tools · instructor · pydantic" },
    { id:"t2-3", name:"Model Context Protocol (MCP)", freq:4,
      topics:[
        {t:"MCP server setup (FastMCP)",s:"todo"},{t:"Tool & resource registration",s:"todo"},
        {t:"MCP client integration",s:"todo"},{t:"Connecting to Claude Desktop",s:"todo"},
        {t:"Enterprise MCP patterns",s:"todo"},
      ], tools:"mcp · fastmcp · anthropic MCP SDK" },
    { id:"t2-4", name:"Memory systems", freq:4,
      topics:[
        {t:"Conversation window memory",s:"todo"},{t:"Vector long-term memory",s:"todo"},
        {t:"Episodic memory patterns",s:"todo"},{t:"mem0 architecture",s:"todo"},
        {t:"LangGraph checkpointer",s:"have"},
      ], tools:"mem0 · zep · langgraph checkpointer · redis" },
    { id:"t2-5", name:"Agent evaluation & testing", freq:4,
      topics:[
        {t:"LLM-as-judge patterns",s:"todo"},{t:"RAGAS metrics",s:"todo"},
        {t:"Trajectory evaluation",s:"todo"},{t:"Regression test suites",s:"todo"},
        {t:"Dataset-driven eval loops",s:"todo"},
      ], tools:"RAGAS · deepeval · langsmith evals · promptfoo" },
    { id:"t2-6", name:"Autogen / CrewAI / ADK", freq:3,
      topics:[
        {t:"AutoGen ConversableAgent",s:"todo"},{t:"CrewAI role & task definition",s:"todo"},
        {t:"Google ADK agent setup",s:"todo"},{t:"Framework comparison",s:"todo"},
        {t:"When to use which framework",s:"todo"},
      ], tools:"autogen · crewai · google-adk · smolagents" },
  ],
  T3:[
    { id:"t3-1", name:"LangSmith / tracing", freq:5,
      topics:[
        {t:"Project setup & API keys",s:"have"},{t:"Run tracing & span hierarchy",s:"have"},
        {t:"Prompt versioning & datasets",s:"todo"},{t:"A/B evaluation in LangSmith",s:"todo"},
        {t:"Custom feedback & annotation",s:"have"},
      ], tools:"langsmith · phoenix (Arize) · langfuse · opentelemetry" },
    { id:"t3-2", name:"MLflow / Weights & Biases", freq:4,
      topics:[
        {t:"Experiment tracking runs",s:"have"},{t:"Model registry & versioning",s:"todo"},
        {t:"W&B prompts for LLMs",s:"todo"},{t:"Artifact logging",s:"todo"},
        {t:"Hyperparameter sweeps",s:"todo"},
      ], tools:"mlflow · wandb · clearml · neptune" },
    { id:"t3-3", name:"Model serving & deployment", freq:4,
      topics:[
        {t:"vLLM for high-throughput serving",s:"todo"},{t:"TGI (Text Generation Inference)",s:"todo"},
        {t:"Ollama for local dev",s:"have"},{t:"SageMaker real-time endpoints",s:"todo"},
        {t:"Batching & continuous batching",s:"todo"},
      ], tools:"vllm · tgi · ollama · sagemaker · vertex ai" },
    { id:"t3-4", name:"Kubernetes & Docker for ML", freq:4,
      topics:[
        {t:"Dockerfile for LLM apps",s:"todo"},{t:"K8s Deployments & Services",s:"todo"},
        {t:"GPU node selectors",s:"todo"},{t:"Helm chart basics",s:"todo"},
        {t:"ArgoCD GitOps workflow",s:"todo"},
      ], tools:"docker · kubectl · helm · argocd · kubeflow" },
    { id:"t3-5", name:"CI/CD for ML pipelines", freq:3,
      topics:[
        {t:"GitHub Actions for model deploy",s:"have"},{t:"Automated eval gates in CI",s:"todo"},
        {t:"DVC for data versioning",s:"todo"},{t:"Model promotion workflows",s:"todo"},
        {t:"Rollback strategies",s:"todo"},
      ], tools:"github-actions · argocd · dvc · jenkins" },
    { id:"t3-6", name:"Observability stack", freq:3,
      topics:[
        {t:"Prometheus metrics for LLM APIs",s:"todo"},{t:"Grafana dashboards",s:"have"},
        {t:"Distributed tracing (Jaeger)",s:"todo"},{t:"Latency percentiles & SLOs",s:"todo"},
        {t:"Alert rules for degradation",s:"todo"},
      ], tools:"prometheus · grafana · opentelemetry · jaeger" },
  ],
  T4:[
    { id:"t4-1", name:"SFT (supervised fine-tuning)", freq:4,
      topics:[
        {t:"Instruction dataset formats",s:"learn"},{t:"Training loop with TRL SFTTrainer",s:"learn"},
        {t:"Loss curves & overfitting",s:"learn"},{t:"Chat template formatting",s:"todo"},
        {t:"Compute & VRAM requirements",s:"todo"},
      ], tools:"transformers · trl · axolotl · unsloth" },
    { id:"t4-2", name:"LoRA / QLoRA / PEFT", freq:4,
      topics:[
        {t:"LoRA rank & alpha selection",s:"todo"},{t:"QLoRA with 4-bit quantisation",s:"todo"},
        {t:"Target modules (q_proj, v_proj)",s:"todo"},{t:"Adapter merging & export",s:"todo"},
        {t:"Memory efficiency benchmarks",s:"todo"},
      ], tools:"peft · bitsandbytes · unsloth · mergekit" },
    { id:"t4-3", name:"RLHF & DPO", freq:3,
      topics:[
        {t:"Reward model training",s:"learn"},{t:"DPO preference dataset format",s:"learn"},
        {t:"DPOTrainer from TRL",s:"todo"},{t:"ORPO & SimPO variants",s:"todo"},
        {t:"When SFT beats RLHF",s:"todo"},
      ], tools:"trl · DPOTrainer · openrlhf · lm-human-preferences" },
    { id:"t4-4", name:"Quantisation & optimisation", freq:3,
      topics:[
        {t:"GGUF format & llama.cpp",s:"todo"},{t:"AWQ vs GPTQ vs GGUF",s:"todo"},
        {t:"Inference speed benchmarking",s:"todo"},{t:"Flash Attention 2",s:"todo"},
        {t:"Speculative decoding basics",s:"todo"},
      ], tools:"llama.cpp · auto-awq · optimum · exllama2" },
    { id:"t4-5", name:"Dataset curation & annotation", freq:3,
      topics:[
        {t:"Alpaca & ShareGPT formats",s:"todo"},{t:"Quality filtering heuristics",s:"todo"},
        {t:"Deduplication strategies",s:"todo"},{t:"Argilla annotation UI",s:"todo"},
        {t:"Synthetic data with LLMs",s:"todo"},
      ], tools:"datasets · argilla · label-studio · distilabel" },
    { id:"t4-6", name:"Eval frameworks for fine-tuned models", freq:3,
      topics:[
        {t:"lm-evaluation-harness tasks",s:"todo"},{t:"MT-Bench & AlpacaEval",s:"todo"},
        {t:"Custom domain eval design",s:"todo"},{t:"MMLU & HumanEval",s:"todo"},
        {t:"Regression vs capability evals",s:"todo"},
      ], tools:"lm-evaluation-harness · openai-evals · mt-bench" },
  ],
  T5:[
    { id:"t5-1", name:"AWS (Bedrock, Lambda, SageMaker)", freq:5,
      topics:[
        {t:"Bedrock model invocation API",s:"todo"},{t:"Lambda for serverless inference",s:"todo"},
        {t:"S3 for document storage (RAG)",s:"todo"},{t:"SageMaker training jobs",s:"todo"},
        {t:"IAM roles & least privilege",s:"todo"},
      ], tools:"boto3 · sagemaker-python-sdk · aws-cdk · langchain-aws" },
    { id:"t5-2", name:"Azure (OpenAI, ML, Cognitive Search)", freq:4,
      topics:[
        {t:"Azure OpenAI endpoint setup",s:"todo"},{t:"Azure Cognitive Search for RAG",s:"todo"},
        {t:"Azure ML pipelines",s:"todo"},{t:"Managed online endpoints",s:"todo"},
        {t:"Azure Key Vault for secrets",s:"todo"},
      ], tools:"azure-ai-inference · azure-search · azure-identity" },
    { id:"t5-3", name:"GCP (Vertex AI, BigQuery ML)", freq:3,
      topics:[
        {t:"Vertex AI model garden",s:"todo"},{t:"Gemini API in Vertex",s:"todo"},
        {t:"BigQuery ML for embeddings",s:"todo"},{t:"Vertex pipelines (Kubeflow)",s:"todo"},
        {t:"Cloud Run for LLM APIs",s:"todo"},
      ], tools:"google-cloud-aiplatform · vertexai · bigquery-ml" },
    { id:"t5-4", name:"REST API design", freq:5,
      topics:[
        {t:"FastAPI route & dependency injection",s:"have"},{t:"Request/response models with Pydantic",s:"have"},
        {t:"Auth middleware (OAuth2, API keys)",s:"have"},{t:"Rate limiting & throttling",s:"have"},
        {t:"API versioning strategies",s:"have"},
      ], tools:"fastapi · uvicorn · pydantic · slowapi" },
    { id:"t5-5", name:"Authentication (OAuth2, JWT)", freq:3,
      topics:[
        {t:"JWT creation & validation",s:"have"},{t:"OAuth2 password & bearer flow",s:"have"},
        {t:"FastAPI security utilities",s:"have"},{t:"Token refresh patterns",s:"have"},
        {t:"Secret management (env, vault)",s:"have"},
      ], tools:"python-jose · authlib · fastapi-security · passlib" },
  ],
  T6:[
    { id:"t6-1", name:"Guardrails & safety", freq:4,
      topics:[
        {t:"Guardrails-ai validators",s:"todo"},{t:"NeMo Guardrails dialog flows",s:"todo"},
        {t:"Output schema validation",s:"todo"},{t:"PII detection & redaction",s:"todo"},
        {t:"Toxicity & hallucination filters",s:"todo"},
      ], tools:"guardrails-ai · nemo-guardrails · llm-guard · presidio" },
    { id:"t6-2", name:"Knowledge graphs", freq:2,
      topics:[
        {t:"Neo4j graph schema design",s:"todo"},{t:"GraphRAG (Microsoft)",s:"todo"},
        {t:"Entity extraction for graphs",s:"todo"},{t:"Graph + vector hybrid retrieval",s:"todo"},
        {t:"LLM-to-Cypher query generation",s:"todo"},
      ], tools:"neo4j · networkx · graphrag · py2neo" },
    { id:"t6-3", name:"Semantic Kernel", freq:3,
      topics:[
        {t:"SK kernel & plugin setup",s:"todo"},{t:"Memory & planner components",s:"todo"},
        {t:"Copilot Stack integration",s:"todo"},{t:"Azure OpenAI with SK",s:"todo"},
        {t:"Function calling via SK",s:"todo"},
      ], tools:"semantic-kernel · sk-python · copilot-sdk" },
    { id:"t6-4", name:"System design for AI scale", freq:4,
      topics:[
        {t:"Caching (Redis) for LLM responses",s:"have"},{t:"Async task queues (Celery, RQ)",s:"have"},
        {t:"Kafka for event-driven AI",s:"todo"},{t:"Latency budgeting & P99",s:"todo"},
        {t:"Horizontal scaling patterns",s:"have"},
      ], tools:"redis · celery · kafka · rabbitmq · dramatiq" },
    { id:"t6-5", name:"NLP fundamentals", freq:3,
      topics:[
        {t:"Transformer architecture (attention)",s:"have"},{t:"BPE & WordPiece tokenisation",s:"have"},
        {t:"Positional encodings",s:"have"},{t:"Self-attention vs cross-attention",s:"have"},
        {t:"Pre-training vs fine-tuning",s:"have"},
      ], tools:"transformers · tokenizers · datasets · einops" },
    { id:"t6-6", name:"Data pipelines for LLMs", freq:3,
      topics:[
        {t:"Airflow DAGs for RAG ingestion",s:"todo"},{t:"Prefect flows & tasks",s:"todo"},
        {t:"Ray for distributed processing",s:"todo"},{t:"Document parsing (PDFs, HTML)",s:"todo"},
        {t:"Pipeline monitoring & alerting",s:"todo"},
      ], tools:"apache-airflow · prefect · ray · unstructured · docling" },
  ],
};
